### ISSUE TITLE
Merged Manifest Issue while integrating the YOTI_SDK in android using Java with Gradle.

### ISSUE THREAD

**Issue by nikhiapps** [getyoti/yoti-doc-scan-android#11]
#Merged Manifest Issue while integrating the YOTI_SDK in android using Java with Gradle.
Hello warm wishes guys,
i am facing an issue after adding the dependencies in gradle , i am getting the merged manifest 

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processAgentDebugManifest'.
> Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
  	is also present at [androidx.core:core:1.1.0] AndroidManifest.xml:24:18-86 value=(androidx.core.app.CoreComponentFactory).
  	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:22:5-32:19 to override.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
This was the error after Intergration of SDK.
------------------------------------------------------------------------------------------------------------
After replacing   tools:replace="android:appComponentFactory
 this was the error appears again:
* What went wrong:
Execution failed for task ':app:processAgentDebugManifest'.
> Manifest merger failed with multiple errors, see logs

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

i tried the many suggestions like   tools:replace="android:roundIcon,appComponentFactory"
but i am unable to trace the issue after integrating YOTISDK.
thanks in advance...

**Comment by jlmartyres** [comment]
Hi,

We're currently investigating this issue.

Please feel free to direct any further queries to our support team at sdksupport@yoti.com

Kind regards,
Jason

**Comment by jlmartyres** [comment]
Hi,

Please could you send us an email at sdksupport@yoti.com where we would be happy to discuss this issue in greater detail.

Look forward to hearing from you.

Kind regards
Jason
